### ISSUE TITLE
Missing license file.

### ISSUE THREAD

**Issue by grafana-dee** [kor44/gofilter#1]
Hi,

This project has no licence and I need to build something very similar and would like to know whether you consider it open source, and if so what license you are applying to the code.

If you regard it as open and are unsure of license, may I suggest MIT.

Thanks,

David

**Comment by kor44** [comment]
Hello, David!
Yes it's open source and yes MIT license.

I'm very glad, this project is interesting to somedoy.))
If you need some help, I can modify project to meet your requirements.

**Comment by grafana-dee** [comment]
Thanks, much appreciated.

Now I know the license I'll dive in fully :)
